# Generated by Django 5.2.1 on 2025-06-24 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_userprofile_agreed_to_terms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='confirm_password',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='password',
        ),
    ]
