# Generated by Django 5.2.1 on 2025-06-25 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_remove_userprofile_confirm_password_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='agreed_to_terms',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='consent_to_communications',
        ),
        migrations.CreateModel(
            name='UserStripeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_session_id', models.TextField()),
                ('status', models.BooleanField(blank=True, null=True)),
                ('payment_period', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_stripe_session', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
