# Generated by Django 5.2.1 on 2025-06-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_remove_userprofile_agreed_to_terms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstripesession',
            name='stripe_customer_id',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
