# Generated by Django 5.2.1 on 2025-06-27 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_userstripesession_stripe_customer_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserStripeSession',
        ),
    ]
