# Generated by Django 5.2.1 on 2025-06-29 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_delete_userstripesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='agreed_to_terms',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='consent_to_communications',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
